# Only delete stuff after this line if you know what you're doing.
modules:
  # Verification Module
  verification:
    # Disabled because this is aids
    # welcomeChannel: "{{ CHANNELS.WELCOME }}"
  
    permission: "{{ ROLES.MODERATOR }}"
  
    # The role to add to users when they successfully accept the rules.
    verifiedRole: "{{ ROLES.VERIFIED }}"
    
    interactions:
      # The initial message displayed when the /verification is run.
      initialMessageInteractionPath: "verification"
      
      # The interaction to display when the user presses the verification button.
      rulesAcknowledgementInteractionPath: "serverRulesAcknowledgement"
    
    # Verification button settings
    button:
      title: "I understood the rules and I will follow them"
      type: "PRIMARY"
      
      
  supportThreads:
    permission: "{{ ROLES.MODERATOR }}"
    
    configs:
      main:
        displayInteractionPath: "support"
        
        supportThreadConfirmationInteractionPath: "supportDisclaimer"
        supportThreadDisplayInteractionPath: "supportThreadPrompt"
        supportThreadChannel: "{{ CHANNELS.SUPPORT }}"
        supportThreadButton:
          title: "Help"
          type: "PRIMARY"
          
        troubleshootInteractionPath: "self-help"
        troubleshootButton:
          title: "Troubleshoot"
          type: "SUCCESS"
