# Only delete stuff after this line if you know what you're doing.
modules:
  # Verification Module
  verification:
    welcome_channel: "{{ CHANNELS.WELCOME }}"
  
    permission: "{{ ROLES.MODERATOR }}"
  
    # The role to add to users when they successfully accept the rules.
    verified_role: "{{ ROLES.VERIFIED }}"
    
    interactions:
      # The initial message displayed when the /verification is run.
      initial_message: "self-help"
      
      # The interaction to display when the user presses the verification button.
      rules_acknowledgement: "serverRulesAcknowledgement"
    
    # Verification button settings
    button:
      title: "Verify"
      type: "PRIMARY"
