embeds:
- color: 0xECC8F9
  title: "**Paperback Support Instructions**"
  fields:
  - name: "**Provide specific details**"
    value: |
      When reporting an issue, please provide specific details and include screenshots if possible. This will help us diagnose the problem more quickly and effectively. 

      Please include the following information:

      **iOS version:** 
      Example: iOS 18.5
      **App version:** 
      Example: v0.9.0-b1.0.0
      
      Thank you for your cooperation.
