embeds:
- color: 0xECC8F9
  title: "**Paperback Support Instructions**"
  fields:
  - name: "**Provide specific details**"
    value: |
      When reporting an issue, please provide specific details and include screenshots if possible. This will help us diagnose the problem more quickly and effectively. 

      Please include the following information:

      **iOS version:** 
      Example: iOS 14.5
      **App version:** 
      Example: v0.6.0-b1.0.0
      **Source and version:** 
      Example: Mangadex (1.0.0)
      **Title and chapter:** 
      Example: I Was Reincarnated as a Manga App Developer, Chapter 1
      
      Thank you for your cooperation.
