match: "(sources|content) settings"
interaction: app_extensions/contentsettings

channels:
  whitelist:
    - "${ CHANNELS.SUPPORT }"
  blacklist:
    - "${ CHANNELS.WELCOME }"
    - "${ CHANNELS.RULES }"
    - "${ CHANNELS.ANNOUNCEMENTS }"
    - "${ CHANNELS.RELEASES }"
    - "${ CHANNELS.ALPHA_CHAT }"