embeds:
- color: 0xEC736D
  title: "Content Settings for 0.8"
  fields:
  - name: "Information"
    value: |
      To adjust your content settings and allow more mature content to display in Paperback, you need to have a Paperback account. Follow these steps:

      1. Go to the [Paperback Portal](https://portal.paperback.moe/welcome).
      2. Log in with your Paperback account, or create one if you don't have one.
      3. Change the content settings to your liking.
      4. Log out of the app if you were logged in.
      5. Log in again.

      Note: If you set your content settings to "Adult" on the portal, you can restrict what content appears in the app by going into `Settings > General Settings > Content Filtering`.

  - name: "Some common problems"
    value: |
      - **I've updated my settings on the portal, but it hasn't changed in my app.**
        Simply restart the app by removing it from your app switcher.
      - **I have selected 'Adult', but it's not saving my selection.**
        Clear your browser's cache, and then log in to the Portal through an incognito window.
      - **It says 'communication error'.**
        Verify your email and check spam/promotions folder.
      - **My content settings haven't changed yet.**
        Follow steps 4 and 5 again.
